name: CMake Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Create build directory
        run: mkdir -p tests/build

      - name: Configure with CMake
        working-directory: tests/build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: tests/build
        run: cmake --build .

      - name: Run tests
        working-directory: tests/build
        run: ctest --output-on-failure
